server:
  port: ${PORT:8862}
message: Configuracion de local en el servidor levantado!

spring:
     datasource:
       driver-class-name: com.mysql.cj.jdbc.Driver
       password: 12345678
       url: jdbc:mysql://localhost:3306/casoapli?serverTimezone=UTC
       usename: root
     jpa:
      hibernate:
        ddl-auto: update
        database-platform: org.hibernate.dialect.MySQL5Dialect
     cloud:
       config:
         uri: http://localhost:8860
